// Generated by CoffeeScript 1.6.2
(function() {
  var Base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Base = (function() {
    function Base(options) {
      this.options = options;
      this.translate = __bind(this.translate, this);
      if (this.initialize != null) {
        this.initialize();
      }
    }

    Base.prototype.translate = function(command) {
      return command;
    };

    return Base;

  })();

  module.exports = {
    Base: Base
  };

}).call(this);
