// Generated by CoffeeScript 1.6.2
(function() {
  var Base, CommandRunner, TmuxCommandRunner, spawn, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base').Base;

  spawn = require('child_process').spawn;

  CommandRunner = (function(_super) {
    __extends(CommandRunner, _super);

    function CommandRunner() {
      this.run = __bind(this.run, this);      _ref = CommandRunner.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CommandRunner.prototype.run = function(command) {
      var process;

      process = spawn(command);
      return process.stdin.end();
    };

    return CommandRunner;

  })(Base);

  TmuxCommandRunner = (function(_super) {
    __extends(TmuxCommandRunner, _super);

    function TmuxCommandRunner() {
      _ref1 = TmuxCommandRunner.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    TmuxCommandRunner.prototype.translate = function(command) {
      return "tmux " + command;
    };

    return TmuxCommandRunner;

  })(CommandRunner);

  module.exports = {
    CommandRunner: CommandRunner,
    TmuxCommandRunner: TmuxCommandRunner
  };

}).call(this);
