// Generated by CoffeeScript 1.6.2
(function() {
  var CommandRunner, XMX;

  CommandRunner = require('./commands').CommandRunner;

  XMX = (function() {
    var command;

    function XMX() {}

    command = new CommandRunner;

    return XMX;

  })();

  module.exports = XMX;

}).call(this);
